### ISSUE TITLE
confusing package

### ISSUE THREAD

**Issue by KristerV** [alisalaah/livesupport#1]
hey. not sure what this package is about.

Cloning and runnind displays a login, but no registration. what are the details? Also the demo site is offline. (when i checked)

**Comment by acamarata** [comment]
This package was discontinued in favor of the LiveChat started as part of RocketChat

**Comment by KristerV** [comment]
ok

**Comment by acamarata** [comment]
@KristerV if you're interested in continuing this project that adds a Live Chat to the front end of websites let me know.

**Comment by KristerV** [comment]
no need, [tawk](http://tawk.to) is great. thanks.
